### ISSUE TITLE
Missing tods2011.cpp

### ISSUE THREAD

**Issue by MarcusParadies** [lemire/rowreorderingcpplibrary#1]
Dear Daniel,

I just cloned your repository and was about to build it. Then I figured out that the source file 'tods2011.cpp' seems to be missing in the git repository. Could you provide this one as well?

Thanks,
Marcus

**Comment by lemire** [comment]
Thanks. I believe I have no added all the missing files. Sorry about that.

(This repo was created hastily soon after the closure of Google code.)
